feat: change to new prod

diff --git a/.github/workflows/operator-manual-deploy-pipeline.yml b/.github/workflows/operator-manual-deploy-pipeline.yml
--- a/.github/workflows/operator-manual-deploy-pipeline.yml
+++ b/.github/workflows/operator-manual-deploy-pipeline.yml
@@ -62,7 +62,7 @@ jobs:
       ENVIRONMENT: ${{ github.event.inputs.environment }}
     steps:
       - name: Configure AWS Credentials
-        uses: aws-actions/configure-aws-credentials@v4
+        uses: aws-actions/configure-aws-credentials@v1
         with:
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID  }}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
@@ -118,7 +118,7 @@ jobs:
       ENVIRONMENT: ${{ github.event.inputs.environment }}
     steps:
       - name: Configure AWS Credentials
-        uses: aws-actions/configure-aws-credentials@v4
+        uses: aws-actions/configure-aws-credentials@v1
         with:
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID  }}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
@@ -170,77 +170,95 @@ jobs:
     if: ${{ github.event.inputs.environment == 'ci' }}
     env:
       DIRECTORY: ${{ github.workspace }}/devops/jcloud/ci/eks
-      AWS_CONFIG_FILE: ${{ github.workspace }}/devops/jina/dev/init/aws_config_actioner
-    steps:
-      - uses: actions/checkout@v3
-        with:
-          repository: jina-ai/jina-infra
-          ref: main
-          token: ${{ secrets.JINA_DEV_BOT }}
-      - name: configure aws credentials
-        uses: aws-actions/configure-aws-credentials@v4
-        with:
-          role-to-assume: arn:aws:iam::458227521111:role/github-actioner-jina-infra
-          role-session-name: jinainfraapply
-          aws-region: us-east-1
-      - name: Setup Terraform
-        uses: hashicorp/setup-terraform@v2
-        with:
-          terraform_version: 1.5.5
-      - name: Terraform Format Check
-        id: fmt
-        working-directory: ${{ github.workspace }}/devops/jcloud/ci/eks
-        run: |
-          terraform fmt -check -diff -write=false
-      - name: Terraform Init
-        id: init
-        working-directory: ${{ github.workspace }}/devops/jcloud/ci/eks
-        run: |
-          git config --global url."https://api:${{ secrets.JINA_DEV_BOT }}@github.com/".insteadOf "https://github.com/"
-          terraform init
-      - name: Terraform Validate
-        id: validate
-        working-directory: ${{ github.workspace }}/devops/jcloud/ci/eks
-        run: |
-          terraform validate -no-color
-      - name: Terraform Apply
-        id: apply
-        working-directory: ${{ github.workspace }}/devops/jcloud/ci/eks
-        run: |
-          terraform apply -auto-approve -input=false
-      - name: Terraform Re-Apply
-        id: reapply
-        if: ${{ steps.apply.conclusion == 'failure' }}
-        working-directory: ${{ github.workspace }}/devops/jcloud/ci/eks
-        run: |
-          terraform apply -auto-approve -input=false
+      AWS_CONFIG_FILE: ${{ github.workspace }}/profile/aws_config_actioner
+      steps:
+        - name: wait for dispatch finish
+          shell: bash
+          run: |
+            rs=$(curl -H "Authorization: token ${{ secrets.JINA_DEV_BOT }}" \
+              https://api.github.com/repos/jina-ai/jina-infra/actions/workflows \
+              |jq ".workflows |sort_by(.id)[]| .path=\".github/workflows/jcloud-deploy.yml\""|jq -n '[inputs][-1]')
+            id=$(echo $rs|jq ".id")
+            create_at=$(echo $rs|jq -r ".created_at")
+            if [[ ! -z ${id} ]]; then
+              for i in {1..180}
+              do
+                unfinish_id=$(curl -H "Authorization: token ${{ secrets.JINA_DEV_BOT }}" \
+                https://api.github.com/repos/jina-ai/jina-infra/actions/workflows/${id}/runs \
+                |jq ".workflow_runs|sort_by(.id)[]|select(.status!=\"completed\")|.id")
+                echo "latest retrive workflow id ${id} status ${unfinish_id}, ${i}"
+                if [[ ${#a} -gt 0 ]]; then
+                  echo "wait for pevious job to finish"
+                  sleep 6
+                  if [[ ${i} -eq 180 ]];then
+                    echo "wait timeout, quit"
+                    exit 0
+                  fi
+                else
+                  exit 0
+                fi
+              done
+            fi
+            exit 0
+        - name: Repository Dispatch
+          uses: peter-evans/repository-dispatch@v2
+          id: dispatch
+          with:
+            token: ${{ secrets.JINA_DEV_BOT }}
+            repository: jina-ai/jina-infra
+            event-type: jcloud-infra-deploy
+            client-payload: '{"release_token": "${{ secrets.WOLF_INFRA_TOKEN }}", "env": "ci", "destroy_cluster": "false"}'
+        - name: wait for dispatch finish
+          shell: bash
+          run: |
+            sleep 3
+            rs=$(curl -H "Authorization: token ${{ secrets.JINA_DEV_BOT }}" \
+              https://api.github.com/repos/jina-ai/jina-infra/actions/workflows \
+              |jq ".workflows |sort_by(.id)[]| .path=\".github/workflows/jcloud-deploy.yml\""|jq -n '[inputs][-1]')
+            id=$(echo $rs|jq ".id")
+            create_at=$(echo $rs|jq -r ".created_at")
+            if [[ $(expr $(date +%s) - $(data -d ${create_at} +%s)) -le 60 ]]; then
+              if [[ ! -z ${id} ]]; then
+                for i in {1..300}
+                do
+                  conclusion=$(curl -H "Authorization: token ${{ secrets.JINA_DEV_BOT }}" \
+                  https://api.github.com/repos/jina-ai/jina-infra/actions/workflows/${id}/runs \
+                  |jq ".workflow_runs|sort_by(.id)[]"|jq -nr '[inputs][-1].conclusion')
+                  echo "latest retrive workflow id ${id} conclusion ${conclusion}, ${i}"
+                  if [[ ${conclusion} == "success" ]]; then
+                    exit 0
+                  elif [[ ${conclusion} == "failure" ]]; then
+                    echo "job failure"
+                    exit 1
+                  fi
+                  sleep 6
+                done
+              fi
+            fi
+            failed to get dispatched job, please check the status of workflow jcloud-deploy.yml in jina-infra repo
+            exit 1
   deployment-ci:
     needs: [build-api-manager, build-operator, terraform-deploy]
     runs-on: ubuntu-latest
-    if: ${{ github.event.inputs.environment }} == "ci"
+    if: ${{ github.event.inputs.environment == 'ci' }}
     env:
       ENVIRONMENT: ${{ github.event.inputs.environment }}
     steps:
       - name: Configure AWS Credentials
-        uses: aws-actions/configure-aws-credentials@v4
+        uses: aws-actions/configure-aws-credentials@v2
         with:
-          aws-access-key-id: ${{ secrets.WOLF_AWS_ACCESS_KEY_ID  }}
-          aws-secret-access-key: ${{ secrets.WOLF_AWS_SECRET_ACCESS_KEY }}
+          role-to-assume: arn:aws:iam::458227521111:role/github-reader-jina-infra
+          role-session-name: jinainfraapply
           aws-region: us-east-1
-      - uses: actions/checkout@v3
-        with:
-          repository: jina-ai/jina-operator
-          ref: ${{ github.event.inputs.branch }}
-          token: ${{ secrets.JINA_DEV_BOT }}
       - name: Get remote state
         uses: dflook/terraform-remote-state@v1
         id: remote-state
         with:
           backend_type: s3
           backend_config: |
-            bucket=jina-terraform-state
-            key=jcloud/${{ github.event.inputs.environment }}/eks/${{ github.event.inputs.eks_region }}
-            region=us-east-2
+            bucket=jina-infra-terraform-state
+            key=jcloud/ci/eks
+            region=us-east-1
       - name: Set environment variables
         run: |
           # Short name for current branch. For PRs, use target branch (base ref)
@@ -296,21 +314,21 @@ jobs:
   deployment:
     needs: [build-api-manager, build-operator]
     runs-on: ubuntu-latest
-    if: ${{ github.event.inputs.environment }} == "dev" || ${{ github.event.inputs.environment }} == "prod"
+    if: ${{ github.event.inputs.environment == 'dev' }}
     env:
       ENVIRONMENT: ${{ github.event.inputs.environment }}
     steps:
-      - name: Configure AWS Credentials
-        uses: aws-actions/configure-aws-credentials@v4
-        with:
-          aws-access-key-id: ${{ secrets.WOLF_AWS_ACCESS_KEY_ID  }}
-          aws-secret-access-key: ${{ secrets.WOLF_AWS_SECRET_ACCESS_KEY }}
-          aws-region: us-east-1
       - uses: actions/checkout@v3
         with:
           repository: jina-ai/jina-operator
           ref: ${{ github.event.inputs.branch }}
           token: ${{ secrets.JINA_DEV_BOT }}
+      - name: Configure AWS Credentials
+        uses: aws-actions/configure-aws-credentials@v1
+        with:
+          aws-access-key-id: ${{ secrets.WOLF_AWS_ACCESS_KEY_ID  }}
+          aws-secret-access-key: ${{ secrets.WOLF_AWS_SECRET_ACCESS_KEY }}
+          aws-region: us-east-1
       - name: Get remote state
         uses: dflook/terraform-remote-state@v1
         id: remote-state
@@ -325,6 +343,135 @@ jobs:
           # Short name for current branch. For PRs, use target branch (base ref)
           GIT_BRANCH=${GITHUB_BASE_REF:-${GITHUB_REF#refs/heads/}}
           echo "GIT_BRANCH=$GIT_BRANCH" >> $GITHUB_ENV
+      - name: Configure AWS Credentials
+        if: ${{ github.event.inputs.environment == 'prod' }}
+        uses: aws-actions/configure-aws-credentials@v2
+        with:
+          role-to-assume: arn:aws:iam::317254068723:role/jcloud-deploy-role
+          role-session-name: jcloud-deploy
+          aws-region: us-east-1
+      - name: helm clean
+        run: |
+          aws eks update-kubeconfig --region ${{ steps.remote-state.outputs.region }} --name ${{ steps.remote-state.outputs.cluster_name }}
+          if helm list -n jcloud | grep -q jcloud-operator; then
+            helm uninstall -n jcloud jcloud-operator
+          fi
+          kubectl delete -f $GITHUB_WORKSPACE/deployment/charts/jcloud-operator/crds/ || true
+        if: github.event.inputs.environment != 'prod'
+      - name: "Update Helm Charts Image sha"
+        run: |
+          sudo snap install yq
+          yq -i ".apimanager.image.sha=\"${{needs.build-api-manager.outputs.sha}}\"" .github/ci/${{ github.event.inputs.environment }}-values.yaml
+          yq -i ".operator.image.sha=\"${{needs.build-operator.outputs.sha}}\"" .github/ci/${{ github.event.inputs.environment }}-values.yaml
+          cat .github/ci/${{ github.event.inputs.environment }}-values.yaml
+      - name: helm deploy
+        run: |
+          cd $GITHUB_WORKSPACE
+          aws eks update-kubeconfig --region ${{ steps.remote-state.outputs.region }} --name ${{ steps.remote-state.outputs.cluster_name }}
+          if [[ -f "$GITHUB_WORKSPACE/api/internals/instances/instances.yml" ]]; then
+            set +e
+            kubectl get configmap jcloud-instances -n jcloud
+            if [[ $? -eq 0 ]]; then
+              kubectl delete configmap jcloud-instances -n jcloud
+            fi
+            kubectl create configmap jcloud-instances --from-file=instances.yml=$GITHUB_WORKSPACE/api/internals/instances/instances.yml -n jcloud
+          fi
+          set -e
+          kubectl apply -f deployment/charts/jcloud-operator/crds/
+          if [[ $GIT_BRANCH == 'main' ]]; then
+            bash ./deployment/scripts/deploy.sh -r ${{ steps.remote-state.outputs.region }} -n ${{ steps.remote-state.outputs.cluster_name }} \
+            -f .github/ci/${{ github.event.inputs.environment }}-values.yaml \
+            --registry 253352124568.dkr.ecr.us-east-2.amazonaws.com --tag latest
+          else
+            if [[ "${{ github.event.inputs.branch }}" == "" ]]; then
+              bash ./deployment/scripts/deploy.sh -r ${{ steps.remote-state.outputs.region }} -n ${{ steps.remote-state.outputs.cluster_name }} \
+              -f .github/ci/${{ github.event.inputs.environment }}-values.yaml \
+              --registry 253352124568.dkr.ecr.us-east-2.amazonaws.com --tag latest
+            else
+              bash ./deployment/scripts/deploy.sh -r ${{ steps.remote-state.outputs.region }} -n ${{ steps.remote-state.outputs.cluster_name }} \
+              -f .github/ci/${{ github.event.inputs.environment }}-values.yaml \
+              --registry 253352124568.dkr.ecr.us-east-2.amazonaws.com --tag ${{ github.event.inputs.branch }}
+            fi
+          fi
+      - name: check if certificate exists
+        id: check_cert
+        if: ${{ github.event.inputs.environment }} == "dev" || ${{ github.event.inputs.environment }} == "prod"
+        run: |
+          cert_name=$([[ "${{ github.event.inputs.environment }}" == "prod" ]] && echo "wolf-tls" || echo "wolf-dev-tls" )
+          echo "cert=`kubectl get cert -n jcloud $cert_name -o name`" >> $GITHUB_OUTPUT
+      - name: deploy certificate
+        if: steps.check_cert.outputs.cert == ''
+        run: |
+          cert_name=$([[ "${{ github.event.inputs.environment }}" == "prod" ]] && echo "wolf-tls" || echo "wolf-dev-tls" )
+          dns_name=$([[ "${{ github.event.inputs.environment }}" == "prod" ]] && echo "*.wolf.jina.ai" || echo "*.dev.wolf.jina.ai" )
+          cat <<EOF | kubectl apply -f -
+          apiVersion: cert-manager.io/v1
+          kind: Certificate
+          metadata:
+            name: $cert_name
+            namespace: jcloud
+          spec:
+            dnsNames:
+            - '$dns_name'
+            issuerRef:
+              group: cert-manager.io
+              kind: ClusterIssuer
+              name: letsencrypt-$cert_name
+            secretName: $cert_name
+            usages:
+            - digital signature
+            - key encipherment
+          EOF
+      - name: set env
+        run: |
+          if [[ ${{ github.event.inputs.environment }} != "prod" ]]; then
+            kubectl set env deploy/jcloud-operator-api-manager -n jcloud MONGO_URI="${{ secrets.JC_CI_MONGO_URI }}" LIST_USER_TOKEN="${{ secrets.LIST_USER_TOKEN }}" JCLOUD_M2M_TOKEN="${{ secrets.JCLOUD_M2M_TOKEN }}"
+            kubectl set env deploy/flow-jcloud-operator -n jcloud MONGO_URI="${{ secrets.JC_CI_MONGO_URI }}" JCLOUD_M2M_TOKEN="${{ secrets.JCLOUD_M2M_TOKEN }}"
+            kubectl set env deploy/deployment-jcloud-operator -n jcloud MONGO_URI="${{ secrets.JC_CI_MONGO_URI }}" JCLOUD_M2M_TOKEN="${{ secrets.JCLOUD_M2M_TOKEN }}"
+          else
+            kubectl set env deploy/jcloud-operator-api-manager -n jcloud MONGO_URI="${{ secrets.PROD_MONGO_URI }}" LIST_USER_TOKEN="${{ secrets.LIST_USER_TOKEN }}" GRAFANA_AUTH_TOKEN="${{ secrets.GRAFANA_AUTH_TOKEN }}" JCLOUD_M2M_TOKEN="${{ secrets.JCLOUD_M2M_TOKEN }}"
+            kubectl set env deploy/flow-jcloud-operator -n jcloud MONGO_URI="${{ secrets.PROD_MONGO_URI }}" JCLOUD_M2M_TOKEN="${{ secrets.JCLOUD_M2M_TOKEN }}"
+            kubectl set env deploy/deployment-jcloud-operator -n jcloud MONGO_URI="${{ secrets.PROD_MONGO_URI }}" JCLOUD_M2M_TOKEN="${{ secrets.JCLOUD_M2M_TOKEN }}"
+          fi      
+  deployment-prod:
+    needs: [build-api-manager, build-operator]
+    runs-on: ubuntu-latest
+    if: ${{ github.event.inputs.environment == 'prod' }}
+    env:
+      ENVIRONMENT: ${{ github.event.inputs.environment }}
+    steps:
+      - uses: actions/checkout@v3
+        with:
+          repository: jina-ai/jina-operator
+          ref: ${{ github.event.inputs.branch }}
+          token: ${{ secrets.JINA_DEV_BOT }}
+      - name: Configure AWS Credentials
+        uses: aws-actions/configure-aws-credentials@v2
+        with:
+          role-to-assume: arn:aws:iam::317254068723:role/github-reader-jina-infra
+          role-session-name: jinainfraapply
+          aws-region: us-east-1
+      - name: Get remote state
+        uses: dflook/terraform-remote-state@v1
+        id: remote-state
+        with:
+          backend_type: s3
+          backend_config: |
+            bucket=jina-prod-infra-terraform-state
+            key=jcloud/prod/eks/us-east-1
+            region=us-east-1
+      - name: Set environment variables
+        run: |
+          # Short name for current branch. For PRs, use target branch (base ref)
+          GIT_BRANCH=${GITHUB_BASE_REF:-${GITHUB_REF#refs/heads/}}
+          echo "GIT_BRANCH=$GIT_BRANCH" >> $GITHUB_ENV
+      - name: Configure AWS Credentials
+        uses: aws-actions/configure-aws-credentials@v2
+        with:
+          role-to-assume: arn:aws:iam::317254068723:role/jcloud-deploy-role
+          unset-current-credentials: true
+          role-session-name: jcloud-deploy
+          aws-region: us-east-1
       - name: helm clean
         run: |
           aws eks update-kubeconfig --region ${{ steps.remote-state.outputs.region }} --name ${{ steps.remote-state.outputs.cluster_name }}
