chore: disable all tests

diff --git a/.github/workflows/operator-integration-tests-v2.yml b/.github/workflows/operator-integration-tests-v2.yml
--- a/.github/workflows/operator-integration-tests-v2.yml
+++ b/.github/workflows/operator-integration-tests-v2.yml
@@ -325,245 +325,245 @@ jobs:
           JCLOUD_LOGLEVEL: DEBUG
           JINA_AUTH_TOKEN: ${{ env._WOLF_NPRD_GENERAL_WOLF_TOKEN }}
 
-  operator:
-    needs: [prep-testbed-operator, set-env]
-    runs-on: ubuntu-latest
-    strategy:
-      max-parallel: 4
-      fail-fast: false
-      matrix:
-        test-path: ${{fromJson(needs.prep-testbed-operator.outputs.matrix)}}
-    steps:
-      - name: Checkout Repo
-        uses: actions/checkout@v3
-        with:
-          repository: jina-ai/jina-operator
-          ref: ${{ github.event.inputs.branch }}
-          token: ${{ secrets.JINA_DEV_BOT }}
+  # operator:
+  #   needs: [prep-testbed-operator, set-env]
+  #   runs-on: ubuntu-latest
+  #   strategy:
+  #     max-parallel: 4
+  #     fail-fast: false
+  #     matrix:
+  #       test-path: ${{fromJson(needs.prep-testbed-operator.outputs.matrix)}}
+  #   steps:
+  #     - name: Checkout Repo
+  #       uses: actions/checkout@v3
+  #       with:
+  #         repository: jina-ai/jina-operator
+  #         ref: ${{ github.event.inputs.branch }}
+  #         token: ${{ secrets.JINA_DEV_BOT }}
 
-      - name: Cache Go Modules
-        uses: actions/cache@v2
-        with:
-          path: |
-            ~/.cache/go-build
-            ~/go/pkg/mod
-          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
-          restore-keys: |
-            ${{ runner.os }}-go-
+  #     - name: Cache Go Modules
+  #       uses: actions/cache@v2
+  #       with:
+  #         path: |
+  #           ~/.cache/go-build
+  #           ~/go/pkg/mod
+  #         key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
+  #         restore-keys: |
+  #           ${{ runner.os }}-go-
 
-      - name: Cache Python Dependencies
-        uses: actions/cache@v2
-        with:
-          path: ~/.cache/pip
-          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
-          restore-keys: |
-            ${{ runner.os }}-pip-
+  #     - name: Cache Python Dependencies
+  #       uses: actions/cache@v2
+  #       with:
+  #         path: ~/.cache/pip
+  #         key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
+  #         restore-keys: |
+  #           ${{ runner.os }}-pip-
 
-      - name: Set up Golang 1.18
-        uses: actions/setup-go@v3
-        with:
-          go-version: 1.18
+  #     - name: Set up Golang 1.18
+  #       uses: actions/setup-go@v3
+  #       with:
+  #         go-version: 1.18
 
-      - name: Set up Python 3.7
-        uses: actions/setup-python@v2
-        with:
-          python-version: 3.7
+  #     - name: Set up Python 3.7
+  #       uses: actions/setup-python@v2
+  #       with:
+  #         python-version: 3.7
 
-      - name: Install Jina
-        run: |
-          pip3 install jina
+  #     - name: Install Jina
+  #       run: |
+  #         pip3 install jina
 
-      - name: Install Dependencies
-        run: |
-          go install github.com/onsi/ginkgo/v2/ginkgo@v2.6.1
-          go get github.com/onsi/gomega/...
-          go mod tidy -v
-        working-directory: ./operator
+  #     - name: Install Dependencies
+  #       run: |
+  #         go install github.com/onsi/ginkgo/v2/ginkgo@v2.6.1
+  #         go get github.com/onsi/gomega/...
+  #         go mod tidy -v
+  #       working-directory: ./operator
 
-      - name: Configure AWS Credentials
-        uses: aws-actions/configure-aws-credentials@v1
-        with:
-          aws-access-key-id: ${{ secrets.WOLF_AWS_ACCESS_KEY_ID }}
-          aws-secret-access-key: ${{ secrets.WOLF_AWS_SECRET_ACCESS_KEY }}
-          aws-region: us-east-1
+  #     - name: Configure AWS Credentials
+  #       uses: aws-actions/configure-aws-credentials@v1
+  #       with:
+  #         aws-access-key-id: ${{ secrets.WOLF_AWS_ACCESS_KEY_ID }}
+  #         aws-secret-access-key: ${{ secrets.WOLF_AWS_SECRET_ACCESS_KEY }}
+  #         aws-region: us-east-1
 
-      - name: Update Cluster Config
-        run: aws eks update-kubeconfig --region ${{ needs.set-env.outputs.region }} --name ${{ needs.set-env.outputs.cluster }}
+  #     - name: Update Cluster Config
+  #       run: aws eks update-kubeconfig --region ${{ needs.set-env.outputs.region }} --name ${{ needs.set-env.outputs.cluster }}
 
-      - name: Run E2E Integration Test Suites for Operator
-        run: |
-          focus_files=$(echo ${{ matrix.test-path }} | xargs -n1 | xargs -I{} echo "--focus-file controllers/test/e2e/{}" | xargs)
-          ginkgo ${focus_files} -v --progress ./...
-        env:
-          ACK_GINKGO_RC: true
-          ACK_GINKGO_DEPRECATIONS: 2.6.1
-        working-directory: ./operator
-        timeout-minutes: 30
+  #     - name: Run E2E Integration Test Suites for Operator
+  #       run: |
+  #         focus_files=$(echo ${{ matrix.test-path }} | xargs -n1 | xargs -I{} echo "--focus-file controllers/test/e2e/{}" | xargs)
+  #         ginkgo ${focus_files} -v --progress ./...
+  #       env:
+  #         ACK_GINKGO_RC: true
+  #         ACK_GINKGO_DEPRECATIONS: 2.6.1
+  #       working-directory: ./operator
+  #       timeout-minutes: 30
 
-      - if: failure()
-        uses: 8398a7/action-slack@v3
-        with:
-          status: ${{ job.status }}
-          fields: eventName,job
-          text: |
-            :no_entry: `${{ matrix.test-path }}` failed for branch `${{ github.event.inputs.branch }}` (cluster: `${{ github.event.inputs.env }}`)
-          author_name: ":cloud: Operator Integration Tests"
-        env:
-          SLACK_WEBHOOK_URL: ${{ secrets.WOLF_SLACK_NIGHTLY_TESTS_WEBHOOK }}
-          MATRIX_CONTEXT: ${{ toJson(matrix) }}
+  #     - if: failure()
+  #       uses: 8398a7/action-slack@v3
+  #       with:
+  #         status: ${{ job.status }}
+  #         fields: eventName,job
+  #         text: |
+  #           :no_entry: `${{ matrix.test-path }}` failed for branch `${{ github.event.inputs.branch }}` (cluster: `${{ github.event.inputs.env }}`)
+  #         author_name: ":cloud: Operator Integration Tests"
+  #       env:
+  #         SLACK_WEBHOOK_URL: ${{ secrets.WOLF_SLACK_NIGHTLY_TESTS_WEBHOOK }}
+  #         MATRIX_CONTEXT: ${{ toJson(matrix) }}
 
-  api:
-    needs: [prep-testbed-api, set-env]
-    runs-on: ubuntu-latest
-    strategy:
-      max-parallel: 4
-      fail-fast: false
-      matrix:
-        test-path: ${{fromJson(needs.prep-testbed-api.outputs.matrix)}}
-    steps:
-      - uses: actions/checkout@v3
-        with:
-          repository: jina-ai/jina-operator
-          ref: ${{ github.event.inputs.branch }}
-          token: ${{ secrets.JINA_DEV_BOT }}
+  # api:
+  #   needs: [prep-testbed-api, set-env]
+  #   runs-on: ubuntu-latest
+  #   strategy:
+  #     max-parallel: 4
+  #     fail-fast: false
+  #     matrix:
+  #       test-path: ${{fromJson(needs.prep-testbed-api.outputs.matrix)}}
+  #   steps:
+  #     - uses: actions/checkout@v3
+  #       with:
+  #         repository: jina-ai/jina-operator
+  #         ref: ${{ github.event.inputs.branch }}
+  #         token: ${{ secrets.JINA_DEV_BOT }}
 
-      - name: Cache Go Modules
-        uses: actions/cache@v2
-        with:
-          path: |
-            ~/.cache/go-build
-            ~/go/pkg/mod
-          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
-          restore-keys: |
-            ${{ runner.os }}-go-
+  #     - name: Cache Go Modules
+  #       uses: actions/cache@v2
+  #       with:
+  #         path: |
+  #           ~/.cache/go-build
+  #           ~/go/pkg/mod
+  #         key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
+  #         restore-keys: |
+  #           ${{ runner.os }}-go-
 
-      - name: Cache Python Dependencies
-        uses: actions/cache@v2
-        with:
-          path: ~/.cache/pip
-          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
-          restore-keys: |
-            ${{ runner.os }}-pip-
+  #     - name: Cache Python Dependencies
+  #       uses: actions/cache@v2
+  #       with:
+  #         path: ~/.cache/pip
+  #         key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
+  #         restore-keys: |
+  #           ${{ runner.os }}-pip-
 
-      - name: Set up Golang 1.18
-        uses: actions/setup-go@v3
-        with:
-          go-version: 1.18
+  #     - name: Set up Golang 1.18
+  #       uses: actions/setup-go@v3
+  #       with:
+  #         go-version: 1.18
 
-      - name: Set up Python 3.7
-        uses: actions/setup-python@v2
-        with:
-          python-version: 3.7
+  #     - name: Set up Python 3.7
+  #       uses: actions/setup-python@v2
+  #       with:
+  #         python-version: 3.7
 
-      - name: Install Dependencies
-        run: |
-          go install github.com/onsi/ginkgo/v2/ginkgo@v2.6.1
-          go get github.com/onsi/gomega/...
-          go mod tidy -v
-        working-directory: ./api
+  #     - name: Install Dependencies
+  #       run: |
+  #         go install github.com/onsi/ginkgo/v2/ginkgo@v2.6.1
+  #         go get github.com/onsi/gomega/...
+  #         go mod tidy -v
+  #       working-directory: ./api
 
-      - name: Configure AWS Credentials
-        uses: aws-actions/configure-aws-credentials@v1
-        with:
-          aws-access-key-id: ${{ secrets.WOLF_AWS_ACCESS_KEY_ID }}
-          aws-secret-access-key: ${{ secrets.WOLF_AWS_SECRET_ACCESS_KEY }}
-          aws-region: us-east-1
+  #     - name: Configure AWS Credentials
+  #       uses: aws-actions/configure-aws-credentials@v1
+  #       with:
+  #         aws-access-key-id: ${{ secrets.WOLF_AWS_ACCESS_KEY_ID }}
+  #         aws-secret-access-key: ${{ secrets.WOLF_AWS_SECRET_ACCESS_KEY }}
+  #         aws-region: us-east-1
 
-      - name: Update Cluster Config
-        run: aws eks update-kubeconfig --region ${{ needs.set-env.outputs.region }} --name ${{ needs.set-env.outputs.cluster }}
+  #     - name: Update Cluster Config
+  #       run: aws eks update-kubeconfig --region ${{ needs.set-env.outputs.region }} --name ${{ needs.set-env.outputs.cluster }}
 
-      - name: Make sure API is healthy
-        run: |
-          for i in {1..180}
-          do
-            STATUS_CODE=`curl -s -o /dev/null -w "%{http_code}" https://${{ needs.set-env.outputs.host }}`
-            if [[ ${STATUS_CODE} -ge 200 ]] && [[ ${STATUS_CODE} -lt 300 ]]; then
-              echo "API ${{ needs.set-env.outputs.host }} returns ${STATUS_CODE}, continue."
-              exit 0
-            fi
-            echo "API ${{ needs.set-env.outputs.host }} returns ${STATUS_CODE}, retry ${1}."
-            sleep 2
-          done
-          exit 1
+  #     - name: Make sure API is healthy
+  #       run: |
+  #         for i in {1..180}
+  #         do
+  #           STATUS_CODE=`curl -s -o /dev/null -w "%{http_code}" https://${{ needs.set-env.outputs.host }}`
+  #           if [[ ${STATUS_CODE} -ge 200 ]] && [[ ${STATUS_CODE} -lt 300 ]]; then
+  #             echo "API ${{ needs.set-env.outputs.host }} returns ${STATUS_CODE}, continue."
+  #             exit 0
+  #           fi
+  #           echo "API ${{ needs.set-env.outputs.host }} returns ${STATUS_CODE}, retry ${1}."
+  #           sleep 2
+  #         done
+  #         exit 1
 
-      - name: Run E2E Integration Test Suites for API
-        run: |
-          focus_files=$(echo ${{ matrix.test-path }} | xargs -n1 | xargs -I{} echo "--focus-file test/e2e/{}" | xargs)
-          ginkgo ${focus_files} -v --progress ./...
-        env:
-          API_HOST: https://${{ needs.set-env.outputs.host }}
-          ACK_GINKGO_RC: true
-          ACK_GINKGO_DEPRECATIONS: 2.5.0
-          FIRST_USER_TOKEN: ${{ secrets.JC_CI_FIRST_USER_TOKEN }}
-          SECOND_USER_TOKEN: ${{ secrets.JC_CI_SECOND_USER_TOKEN }}
-        working-directory: ./api
-        timeout-minutes: 30
+  #     - name: Run E2E Integration Test Suites for API
+  #       run: |
+  #         focus_files=$(echo ${{ matrix.test-path }} | xargs -n1 | xargs -I{} echo "--focus-file test/e2e/{}" | xargs)
+  #         ginkgo ${focus_files} -v --progress ./...
+  #       env:
+  #         API_HOST: https://${{ needs.set-env.outputs.host }}
+  #         ACK_GINKGO_RC: true
+  #         ACK_GINKGO_DEPRECATIONS: 2.5.0
+  #         FIRST_USER_TOKEN: ${{ secrets.JC_CI_FIRST_USER_TOKEN }}
+  #         SECOND_USER_TOKEN: ${{ secrets.JC_CI_SECOND_USER_TOKEN }}
+  #       working-directory: ./api
+  #       timeout-minutes: 30
 
-      - if: failure()
-        uses: 8398a7/action-slack@v3
-        with:
-          status: ${{ job.status }}
-          fields: eventName,job
-          text: |
-            :no_entry: `${{ matrix.test-path }}` failed for branch `${{ github.event.inputs.branch }}` (cluster: `${{ github.event.inputs.env }}`)
-          author_name: ":cloud: API Integration Tests"
-        env:
-          SLACK_WEBHOOK_URL: ${{ secrets.WOLF_SLACK_NIGHTLY_TESTS_WEBHOOK }}
-          MATRIX_CONTEXT: ${{ toJson(matrix) }}
+  #     - if: failure()
+  #       uses: 8398a7/action-slack@v3
+  #       with:
+  #         status: ${{ job.status }}
+  #         fields: eventName,job
+  #         text: |
+  #           :no_entry: `${{ matrix.test-path }}` failed for branch `${{ github.event.inputs.branch }}` (cluster: `${{ github.event.inputs.env }}`)
+  #         author_name: ":cloud: API Integration Tests"
+  #       env:
+  #         SLACK_WEBHOOK_URL: ${{ secrets.WOLF_SLACK_NIGHTLY_TESTS_WEBHOOK }}
+  #         MATRIX_CONTEXT: ${{ toJson(matrix) }}
 
-  compatibility-test:
-    needs:
-      - operator
-      - api
-      - set-env
-    if: ${{ (github.event.inputs.branch != 'main') && (github.event.inputs.only_api_changed == 'false') }}
-    uses: jina-ai/cloud-ops/.github/workflows/operator-backward-compatibility-tests.yml@master
-    secrets: inherit
-    with:
-      branch: ${{ github.event.inputs.branch }}
-      env: ${{ github.event.inputs.env }}
+  # compatibility-test:
+  #   needs:
+  #     - operator
+  #     - api
+  #     - set-env
+  #   if: ${{ (github.event.inputs.branch != 'main') && (github.event.inputs.only_api_changed == 'false') }}
+  #   uses: jina-ai/cloud-ops/.github/workflows/operator-backward-compatibility-tests.yml@master
+  #   secrets: inherit
+  #   with:
+  #     branch: ${{ github.event.inputs.branch }}
+  #     env: ${{ github.event.inputs.env }}
 
-  success-all-test:
-    needs: [compatibility-test, now-integration-tests]
-    if: always()
-    runs-on: ubuntu-latest
-    steps:
-      - uses: technote-space/workflow-conclusion-action@v2
+  # success-all-test:
+  #   needs: [compatibility-test, now-integration-tests]
+  #   if: always()
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - uses: technote-space/workflow-conclusion-action@v2
 
-      - name: Notify success
-        if: env.WORKFLOW_CONCLUSION != 'failure'
-        uses: 8398a7/action-slack@v3
-        with:
-          status: custom
-          fields: repo,author
-          custom_payload: |
-            {
-              attachments: [{
-                text: `:jcloud: Operator + API Tests \n :face_with_raised_eyebrow: Who? :point_right: ${{ github.actor }} \n :face_with_raised_eyebrow: Where? :point_right: ${{ github.event.inputs.env }} \n :face_with_raised_eyebrow: What? :point_right: \`${{ github.event.inputs.branch }}\` \n :question: Status? :white_check_mark:`,
-              }]
-            }
-        env:
-          SLACK_WEBHOOK_URL: ${{ secrets.WOLF_SLACK_NIGHTLY_TESTS_WEBHOOK }}
+  #     - name: Notify success
+  #       if: env.WORKFLOW_CONCLUSION != 'failure'
+  #       uses: 8398a7/action-slack@v3
+  #       with:
+  #         status: custom
+  #         fields: repo,author
+  #         custom_payload: |
+  #           {
+  #             attachments: [{
+  #               text: `:jcloud: Operator + API Tests \n :face_with_raised_eyebrow: Who? :point_right: ${{ github.actor }} \n :face_with_raised_eyebrow: Where? :point_right: ${{ github.event.inputs.env }} \n :face_with_raised_eyebrow: What? :point_right: \`${{ github.event.inputs.branch }}\` \n :question: Status? :white_check_mark:`,
+  #             }]
+  #           }
+  #       env:
+  #         SLACK_WEBHOOK_URL: ${{ secrets.WOLF_SLACK_NIGHTLY_TESTS_WEBHOOK }}
 
-      - name: Notify failure
-        if: env.WORKFLOW_CONCLUSION == 'failure'
-        uses: 8398a7/action-slack@v3
-        with:
-          status: custom
-          fields: repo,author
-          custom_payload: |
-            {
-              attachments: [{
-                text: `:jcloud: Operator + API Tests \n :face_with_raised_eyebrow: Who? :point_right: ${{ github.actor }} \n :face_with_raised_eyebrow: Where? :point_right: ${{ github.event.inputs.env }} \n :face_with_raised_eyebrow: What? :point_right: \`${{ github.event.inputs.branch }}\` \n :question: Status? :x: `,
-              }]
-            }
-        env:
-          SLACK_WEBHOOK_URL: ${{ secrets.WOLF_SLACK_NIGHTLY_TESTS_WEBHOOK }}
+  #     - name: Notify failure
+  #       if: env.WORKFLOW_CONCLUSION == 'failure'
+  #       uses: 8398a7/action-slack@v3
+  #       with:
+  #         status: custom
+  #         fields: repo,author
+  #         custom_payload: |
+  #           {
+  #             attachments: [{
+  #               text: `:jcloud: Operator + API Tests \n :face_with_raised_eyebrow: Who? :point_right: ${{ github.actor }} \n :face_with_raised_eyebrow: Where? :point_right: ${{ github.event.inputs.env }} \n :face_with_raised_eyebrow: What? :point_right: \`${{ github.event.inputs.branch }}\` \n :question: Status? :x: `,
+  #             }]
+  #           }
+  #       env:
+  #         SLACK_WEBHOOK_URL: ${{ secrets.WOLF_SLACK_NIGHTLY_TESTS_WEBHOOK }}
 
-      - name: Check Failure
-        if: env.WORKFLOW_CONCLUSION == 'failure'
-        run: exit 1
+  #     - name: Check Failure
+  #       if: env.WORKFLOW_CONCLUSION == 'failure'
+  #       run: exit 1
 
-      - name: Success
-        if: ${{ success() }}
-        run: echo "All Done"
+  #     - name: Success
+  #       if: ${{ success() }}
+  #       run: echo "All Done"
